spring:
  application:
    name: backend
  profiles:
    active: local

  # 메일 설정 (로컬 개발용)
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}      # 여기에 실제 Gmail 입력
    password: ${SPRING_MAIL_PASSWORD}         # 여기에 앱 비밀번호 입력
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  # 데이터소스 설정 (MySQL)
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

    # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update  # 개발 환경: update, 운영 환경: validate 또는 none
    #    show-sql: true  # 개발 환경에서 SQL 로그 출력
    show-sql: false  # 개발 환경에서 SQL 로그 출력

  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
      password: ${SPRING_REDIS_PASSWORD}
      hibernate:
        format_sql: true  # SQL 포맷팅
        dialect: org.hibernate.dialect.MySQL8Dialect
        use_sql_comments: true  # SQL 주석 표시
    open-in-view: false  # OSIV 비활성화 (권장)

  # batch 설정
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  #oauth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SPRING_GOOGLE_CLIENT_ID}
            client-secret: ${SPRING_GOOGLE_CLIENT_SECRET}
            scope:
              - email

          naver:
            client-id: ${SPRING_NAVER_CLIENT_ID}
            client-secret: ${SPRING_NAVER_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            scope:
              - email

          kakao:
            client-id: ${SPRING_KAKAO_CLIENT_ID}
            client-secret: ${SPRING_KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            scope:

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

# 서버 설정
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# 로깅 설정
logging:
  level:
    root: INFO
    com.example.backend: DEBUG
    org.springframework.security: DEBUG
    #    org.hibernate.SQL: DEBUG
    #    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql.BasicBinder: off
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

toss:
  payments:
    secret-key: ${SPRING_TOSS_SECRET_KEY}  # 환경변수에서 가져오거나 기본값 사용
    base-url: ${SPRING_TOSS_BASE_URL}  # 테스트: https://api.tosspayments.com, 운영: https://api.tosspayments.com